name: JLiveStream
version: '${project.version}'
main: jfbdev.jlivestream.JLiveStream
api-version: '1.16'
description: Plugin to announce live streams, fully customizable.
author: jFrostyBoy

commands:
  live:
    usage: /live <url>
  livestop:
    usage: /livestop
  jlivestreamreload:
    usage: /jlivestreamreload
